exports.react = require('react')
exports['react-dom'] = require('react-dom')
exports['prop-types'] = require('prop-types')
exports.classnames = require('classnames')
exports.proppy = require('proppy')
exports['proppy-react'] = require('proppy-react')